### PR TITLE
Script improvements and additional data format

### PR DESCRIPTION
**Pull request by bradleysepos**
A project I am working on requires ISO 639-2 to ISO 639-1 mapping without the bloat of a full data set, so I added this formatting capability and its output, data/language-codes-3b2.csv. Replacing data/language-codes.csv entirely seems reasonable, but I am uncertain whether any other process already relies on that format.

While implementing the above, I fleshed out the bash script to accept a few useful parameters in order to avoid clobbering existing data, specify alternate input including file input, specify an alternate output path, sanity check everything, and use only awk for formatting (I'm partial to sed but this is slightly more readable). It's more flexible overall and for the usual case it works exactly the same; simply add the "-f" argument to clobber an existing data directory.

Perhaps some or all of this will be useful to the upstream project.

Update: Fixed utf-8 bom being passed through to output in both original data and new format, also add new format to readme.

### CODE REVIEW

**Comment by sxren** [comment]
This is awesome. Thank you very much. I'll commit after hearing back from you on the two questions above. Thanks, again!

**Comment by bradleysepos** [comment]
Aside, http://data.okfn.org/roadmap is currently throwing a TypeError.

**Comment by bradleysepos** [comment]
Latest commits should address comments. Let me know if anything isn't working as expected.

**Comment by bradleysepos** [comment]
Thank you!

I apparently forgot to remove the old bash script (ugh). See https://github.com/datasets/language-codes/pull/2

**Comment by bradleysepos** [comment]
Sounds good regarding `OPTIND=1`, though I will suggest placing it directly above `while getopts ...` for context.

Thanks, the script is now even better than I originally intended.

**Comment by sxren** [comment]
Done. And great! Thank you, again.

**Pull request merged**
