### PR TITLE
[fix][m]: fixed generation script and updated data

### PR DESCRIPTION
**Pull request by Mikanebu**
Rerun script and updated data, so there is no extra empty row in the end.

### CODE REVIEW

**Comment by Mikanebu** [comment]
There is no data in date field from actual source. Probably, it will appear again with next update

**Comment by zelima** [comment]
Looks fine, just thing that date are removed worries a bit

**Comment by Mikanebu** [comment]
In original source, there is no date. Our data is from 2015. This one is updated 2017.

**Comment by zelima** [comment]
Ok, merging

**Pull request merged**
