### PR TITLE
[blankrow][xs]: deleted blank row

### PR DESCRIPTION
**Pull request by Mikanebu**
Deleted blank row since it will not pass a validation

### CODE REVIEW

**Review by anuveyatsu — APPROVED** [review]
LGMT

**Comment by rufuspollock** [comment]
Can you also correct the generation script so we don't get this in future when we rerun the script.

**Comment by Mikanebu** [comment]
@rufuspollock ok, I will take a look

**Comment by Mikanebu** [comment]
Please, check another PR where I fixed generation script.

**Pull request closed without merging**
